/*
 * DO NOT EDIT THIS FILE
 * This file is under version control at
 *   svn://sources.blackfin.uclinux.org/toolchain/trunk/proc-defs/header-frags/
 * and can be replaced with that version at any time
 * DO NOT EDIT THIS FILE
 *
 * Copyright 2004-2012 Analog Devices Inc.
 * Licensed under the Clear BSD license.
 */

/*                                     
                                                                        
 */

#if __SILICON_REVISION__ < 0
# error will not work on BF609 silicon version
#endif

#ifndef _MACH_ANOMALY_H_
#define _MACH_ANOMALY_H_

/*                                                                          */
#define ANOMALY_16000003 (1)
/*                                                     */
#define ANOMALY_16000004 (1)
/*                                                              */
#define ANOMALY_16000005 (1)
/*                                                 */
#define ANOMALY_16000006 (1)
/*                                           */
#define ANOMALY_16000007 (1)
/*                                                    */
#define ANOMALY_16000008 (1)
/*                                           */
#define ANOMALY_16000009 (1)
/*                                                                  */
#define ANOMALY_16000010 (1)
/*                                                         */
#define ANOMALY_16000011 (1)
/*                                                                                      */
#define ANOMALY_16000012 (1)
/*                                                                            */
#define ANOMALY_16000013 (1)
/*                                                                           */
#define ANOMALY_16000014 (1)
/*                                                                                            */
#define ANOMALY_16000015 (1)
/*                                                                  */
#define ANOMALY_16000017 (1)
/*                                                   */
#define ANOMALY_16000018 (1)
/*                                                                    */
#define ANOMALY_16000019 (1)
/*                                                                       */
#define ANOMALY_16000020 (1)
/*                                                                                       */
#define ANOMALY_16000021 (1)
/*                                                  */
#define ANOMALY_16000022 (1)
/*                                                                               */
#define ANOMALY_16000027 (1)
/*                                                    */
#define ANOMALY_16000030 (1)

/*                                         */
#define ANOMALY_05000158 (0)
#define ANOMALY_05000189 (0)
#define ANOMALY_05000198 (0)
#define ANOMALY_05000220 (0)
#define ANOMALY_05000230 (0)
#define ANOMALY_05000231 (0)
#define ANOMALY_05000244 (0)
#define ANOMALY_05000263 (0)
#define ANOMALY_05000273 (0)
#define ANOMALY_05000274 (0)
#define ANOMALY_05000278 (0)
#define ANOMALY_05000281 (0)
#define ANOMALY_05000287 (0)
#define ANOMALY_05000311 (0)
#define ANOMALY_05000312 (0)
#define ANOMALY_05000323 (0)
#define ANOMALY_05000363 (0)
#define ANOMALY_05000380 (0)
#define ANOMALY_05000448 (0)
#define ANOMALY_05000450 (0)
#define ANOMALY_05000456 (0)
#define ANOMALY_05000480 (0)
#define ANOMALY_05000481 (1)

/*                                                         */
#define ANOMALY_05000491 ANOMALY_16000008
#define ANOMALY_05000477 ANOMALY_16000009
#define ANOMALY_05000443 ANOMALY_16000010
#define ANOMALY_05000461 ANOMALY_16000011
#define ANOMALY_05000426 ANOMALY_16000012
#define ANOMALY_05000310 ANOMALY_16000013
#define ANOMALY_05000245 ANOMALY_16000014
#define ANOMALY_05000074 ANOMALY_16000015
#define ANOMALY_05000416 ANOMALY_16000017


#endif
