/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Mon Jan 19 12:21:19 2015
 * Do Not Modify the File.
 */

#ifndef _CUST_KPD_H_
#define _CUST_KPD_H_
#include <linux/input.h>
#include <cust_eint.h>
#define KPD_YES		1
#define KPD_NO		0
/*                                 */
#define KEY_CALL	KEY_SEND
#define KEY_ENDCALL	KEY_END
#undef KEY_OK
#define KEY_OK		KEY_REPLY	/*             */
#define KEY_FOCUS	KEY_HP
#define KEY_AT		KEY_EMAIL
#define KEY_POUND	228	//                  
#define KEY_STAR	227	//                   
#define KEY_DEL 	KEY_BACKSPACE
#define KEY_SYM		KEY_COMPOSE
/*          */
/*          */
/*                */
/*              */
/*          */
/*          */
/*        */
/*          */
/*          */
/*           */
/*            */
/*           */
/*         */
/*           */
/*               */
/*           */
/*         */		/*        */
/*           */
/*             */
/*              */
/*           */
/*            */
/*               */
/*               */
/*
                                                                            
                                                                      
                                                                            
                                             
*/


#define KPD_KEY_DEBOUNCE  1024      /*               */
#define KPD_PWRKEY_MAP    KEY_POWER
#define MTK_PMIC_PWR_KEY    8

/*                                      */
#define KPD_INIT_KEYMAP()	\
{	\
	[19] = KEY_VOLUMEDOWN,		\
	[20] = KEY_VOLUMEUP,		\
}	 
/*                                                               */
/*                                                               */
/*                                                               */
#define KPD_PWRKEY_EINT_GPIO  GPIO0

#define KPD_PWRKEY_GPIO_DIN  0

#define  KPD_DL_KEY1  20    /*              */
#define  KPD_DL_KEY2  19    /*                */
#define  KPD_DL_KEY3  8    /*           */
/*                                                               */
/*                                                             */
/*                                                               */
#define MT65XX_RECOVERY_KEY  20    /*              */
/*                                                               */
/*                                                               */
/*                                                               */
#define KEYS_PWRKEY_MAP		{ KEY_POWER, "Power" }
#define DEFINE_KEYS_KEYMAP(x)		\
 struct key x[] = {     	\
 	KEYS_PWRKEY_MAP,		\
  { KEY_VOLUMEDOWN,   "VLDown"  }, \
  { KEY_VOLUMEUP,   "VLUp"  }, \
}
#define CUST_KEY_UP  KEY_VOLUMEUP   
#define CUST_KEY_VOLUP  KEY_VOLUMEUP   
#define CUST_KEY_DOWN  KEY_VOLUMEDOWN   
#define CUST_KEY_VOLDOWN  KEY_VOLUMEDOWN   
/*                                                               */
/*                                                                 */
/*                                                               */



#endif


