/*****************************************************************************

  (c) Cambridge Silicon Radio Limited 2010
  Confidential information of CSR

  Refer to LICENSE.txt included with this source for details
  on the license terms.

 *****************************************************************************/
#include "csr_wifi_sme_sef.h"

const CsrWifiSmeStateHandlerType CsrWifiSmeUpstreamStateHandlers[CSR_WIFI_SME_PRIM_UPSTREAM_COUNT] =
{
    /*        */ CsrWifiSmeActivateCfmHandler,
    /*        */ CsrWifiSmeAdhocConfigGetCfmHandler,
    /*        */ CsrWifiSmeAdhocConfigSetCfmHandler,
    /*        */ CsrWifiSmeAssociationCompleteIndHandler,
    /*        */ CsrWifiSmeAssociationStartIndHandler,
    /*        */ CsrWifiSmeBlacklistCfmHandler,
    /*        */ CsrWifiSmeCalibrationDataGetCfmHandler,
    /*        */ CsrWifiSmeCalibrationDataSetCfmHandler,
    /*        */ CsrWifiSmeCcxConfigGetCfmHandler,
    /*        */ CsrWifiSmeCcxConfigSetCfmHandler,
    /*        */ CsrWifiSmeCoexConfigGetCfmHandler,
    /*        */ CsrWifiSmeCoexConfigSetCfmHandler,
    /*        */ CsrWifiSmeCoexInfoGetCfmHandler,
    /*        */ CsrWifiSmeConnectCfmHandler,
    /*        */ CsrWifiSmeConnectionConfigGetCfmHandler,
    /*        */ CsrWifiSmeConnectionInfoGetCfmHandler,
    /*        */ CsrWifiSmeConnectionQualityIndHandler,
    /*        */ CsrWifiSmeConnectionStatsGetCfmHandler,
    /*        */ CsrWifiSmeDeactivateCfmHandler,
    /*        */ CsrWifiSmeDisconnectCfmHandler,
    /*        */ CsrWifiSmeEventMaskSetCfmHandler,
    /*        */ CsrWifiSmeHostConfigGetCfmHandler,
    /*        */ CsrWifiSmeHostConfigSetCfmHandler,
    /*        */ CsrWifiSmeIbssStationIndHandler,
    /*        */ CsrWifiSmeKeyCfmHandler,
    /*        */ CsrWifiSmeLinkQualityGetCfmHandler,
    /*        */ CsrWifiSmeMediaStatusIndHandler,
    /*        */ CsrWifiSmeMibConfigGetCfmHandler,
    /*        */ CsrWifiSmeMibConfigSetCfmHandler,
    /*        */ CsrWifiSmeMibGetCfmHandler,
    /*        */ CsrWifiSmeMibGetNextCfmHandler,
    /*        */ CsrWifiSmeMibSetCfmHandler,
    /*        */ CsrWifiSmeMicFailureIndHandler,
    /*        */ CsrWifiSmeMulticastAddressCfmHandler,
    /*        */ CsrWifiSmePacketFilterSetCfmHandler,
    /*        */ CsrWifiSmePermanentMacAddressGetCfmHandler,
    /*        */ CsrWifiSmePmkidCandidateListIndHandler,
    /*        */ CsrWifiSmePmkidCfmHandler,
    /*        */ CsrWifiSmePowerConfigGetCfmHandler,
    /*        */ CsrWifiSmePowerConfigSetCfmHandler,
    /*        */ CsrWifiSmeRegulatoryDomainInfoGetCfmHandler,
    /*        */ CsrWifiSmeRoamCompleteIndHandler,
    /*        */ CsrWifiSmeRoamStartIndHandler,
    /*        */ CsrWifiSmeRoamingConfigGetCfmHandler,
    /*        */ CsrWifiSmeRoamingConfigSetCfmHandler,
    /*        */ CsrWifiSmeScanConfigGetCfmHandler,
    /*        */ CsrWifiSmeScanConfigSetCfmHandler,
    /*        */ CsrWifiSmeScanFullCfmHandler,
    /*        */ CsrWifiSmeScanResultIndHandler,
    /*        */ CsrWifiSmeScanResultsFlushCfmHandler,
    /*        */ CsrWifiSmeScanResultsGetCfmHandler,
    /*        */ CsrWifiSmeSmeStaConfigGetCfmHandler,
    /*        */ CsrWifiSmeSmeStaConfigSetCfmHandler,
    /*        */ CsrWifiSmeStationMacAddressGetCfmHandler,
    /*        */ CsrWifiSmeTspecIndHandler,
    /*        */ CsrWifiSmeTspecCfmHandler,
    /*        */ CsrWifiSmeVersionsGetCfmHandler,
    /*        */ CsrWifiSmeWifiFlightmodeCfmHandler,
    /*        */ CsrWifiSmeWifiOffIndHandler,
    /*        */ CsrWifiSmeWifiOffCfmHandler,
    /*        */ CsrWifiSmeWifiOnCfmHandler,
    /*        */ CsrWifiSmeCloakedSsidsSetCfmHandler,
    /*        */ CsrWifiSmeCloakedSsidsGetCfmHandler,
    /*        */ CsrWifiSmeWifiOnIndHandler,
    /*        */ CsrWifiSmeSmeCommonConfigGetCfmHandler,
    /*        */ CsrWifiSmeSmeCommonConfigSetCfmHandler,
    /*        */ CsrWifiSmeGetInterfaceCapabilityCfmHandler,
    /*        */ CsrWifiSmeErrorIndHandler,
    /*        */ CsrWifiSmeInfoIndHandler,
    /*        */ CsrWifiSmeCoreDumpIndHandler,
    /*        */ CsrWifiSmeAmpStatusChangeIndHandler,
};
